#!/usr/bin/env ruby
require File.expand_path('../../config/environment', __FILE__)

puts "Expiring all fragments..."
Rails.cache.delete_matched /font_details_*/
Rails.cache.delete_matched /sub_font_details_*/

Rails.cache.delete 'popular_users'
Rails.cache.delete 'popular_photos'
Rails.cache.delete 'popular_fonts'
Rails.cache.delete 'popular_fonts_foto_ids_map'
puts "Done."
